[bot]
name="coqbot"
email="coqbot@users.noreply.github.com"

[server]
domain="coqbot.herokuapp.com"

[github]
app_id="31373"

[mappings]
  [mappings.coq]
  github="coq/coq"
  gitlab="coq/coq"

  [mappings.opam-coq-archive]
  github="coq/opam-coq-archive"
  gitlab="coq/opam-coq-archive"

  [mappings.math-comp]
  github="math-comp/math-comp"
  gitlab="math-comp/math-comp"
  gitlab_domain="gitlab.inria.fr"

  [mappings.docker-mathcomp]
  github="math-comp/docker-mathcomp"
  gitlab="math-comp/docker-mathcomp"
  gitlab_domain="gitlab.inria.fr"
